[package]
name = "eva_lib"
version = "0.1.0"
authors = ["Zack Yang <zackyang214@gmail.com>"]
edition = "2018"

[dependencies]
jpeg-decoder = "*"
bmp = "*"
png = "0.14.1"
rand = "0.7.0"
ocl = "0.19"
heapsize = "0.4.2"
lazy_static = "1.3.0"
serde_json = "1.0"